In [23]:
import pandas as pd
import numpy as np

In [41]:
df = pd.read_csv("att_0_1778303821_c3a907.csv", low_memory=False)
# Convert datatype
df['date'] = pd.to_datetime(df['date'])
# Standardize season
df['season'] = df['season'].astype(str)
# Fill null values
df['win_by_runs'] = df['win_by_runs'].fillna(0)
df['win_by_wickets'] = df['win_by_wickets'].fillna(0)
df['wicket_kind'] = df['wicket_kind'].fillna('No Wicket')
df['wicket_player_out'] = df['wicket_player_out'].fillna('None')
# Remove duplicates
df.drop_duplicates(inplace=True)
# Boundary flag
df['is_boundary'] = df['runs_batter'].apply(lambda x: 1 if x in [4,6] else 0)
# Dot ball flag
df['is_dot_ball'] = df['runs_total'].apply(lambda x: 1 if x == 0 else 0)
# Phase classification
def phase(over):
    if over < 6:
        return 'Powerplay'
    elif over <= 15:
        return 'Middle Overs'
    else:
        return 'Death Overs'
df['phase'] = df['over'].apply(phase)

In [25]:
df.head()

,match_id,date,season,event,venue,city,team1,team2,toss_winner,toss_decision,...,runs_total,extras_wides,extras_noballs,extras_byes,extras_legbyes,wicket_kind,wicket_player_out,is_boundary,is_dot_ball,phase
0,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,0,0,0,0,0,No Wicket,None,0,1,Powerplay
1,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,0,0,0,0,0,No Wicket,None,0,1,Powerplay
2,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,4,0,0,0,0,No Wicket,None,1,0,Powerplay
3,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,0,0,0,0,0,No Wicket,None,0,1,Powerplay
4,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,2,2,0,0,0,No Wicket,None,0,0,Powerplay

In [26]:
df.drop_duplicates(inplace=True)

In [27]:
df.shape

(289673, 33)

In [28]:
team_mapping = {
    'Delhi Daredevils': 'Delhi Capitals',
    'Kings XI Punjab': 'Punjab Kings'
}
df.replace(team_mapping, inplace=True)

In [29]:
df.head()

,match_id,date,season,event,venue,city,team1,team2,toss_winner,toss_decision,...,runs_total,extras_wides,extras_noballs,extras_byes,extras_legbyes,wicket_kind,wicket_player_out,is_boundary,is_dot_ball,phase
0,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,0,0,0,0,0,No Wicket,None,0,1,Powerplay
1,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,0,0,0,0,0,No Wicket,None,0,1,Powerplay
2,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,4,0,0,0,0,No Wicket,None,1,0,Powerplay
3,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,0,0,0,0,0,No Wicket,None,0,1,Powerplay
4,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,2,2,0,0,0,No Wicket,None,0,0,Powerplay

In [30]:
columns_to_drop = [
    'event',
    'extras_wides',
    'extras_noballs',
    'extras_byes',
    'extras_legbyes'
]
df.drop(columns=columns_to_drop, inplace=True)

In [31]:
df.head()

,match_id,date,season,venue,city,team1,team2,toss_winner,toss_decision,winner,...,bowler,non_striker,runs_batter,runs_extras,runs_total,wicket_kind,wicket_player_out,is_boundary,is_dot_ball,phase
0,1082591,2017-04-05,2017,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,...,TS Mills,S Dhawan,0,0,0,No Wicket,None,0,1,Powerplay
1,1082591,2017-04-05,2017,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,...,TS Mills,S Dhawan,0,0,0,No Wicket,None,0,1,Powerplay
2,1082591,2017-04-05,2017,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,...,TS Mills,S Dhawan,4,0,4,No Wicket,None,1,0,Powerplay
3,1082591,2017-04-05,2017,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,...,TS Mills,S Dhawan,0,0,0,No Wicket,None,0,1,Powerplay
4,1082591,2017-04-05,2017,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,...,TS Mills,S Dhawan,0,2,2,No Wicket,None,0,0,Powerplay

In [33]:
# Create combined extras column
df['total_extras'] = df['runs_extras']

In [35]:
df.head()

,match_id,date,season,venue,city,team1,team2,toss_winner,toss_decision,winner,...,non_striker,runs_batter,runs_extras,runs_total,wicket_kind,wicket_player_out,is_boundary,is_dot_ball,phase,total_extras
0,1082591,2017-04-05,2017,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,...,S Dhawan,0,0,0,No Wicket,None,0,1,Powerplay,0
1,1082591,2017-04-05,2017,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,...,S Dhawan,0,0,0,No Wicket,None,0,1,Powerplay,0
2,1082591,2017-04-05,2017,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,...,S Dhawan,4,0,4,No Wicket,None,1,0,Powerplay,0
3,1082591,2017-04-05,2017,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,...,S Dhawan,0,0,0,No Wicket,None,0,1,Powerplay,0
4,1082591,2017-04-05,2017,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,...,S Dhawan,0,2,2,No Wicket,None,0,0,Powerplay,2

In [36]:
columns_to_drop = [
    'total_extras'
]
df.drop(columns=columns_to_drop, inplace=True)

In [37]:
df.shape

(289673, 28)

In [40]:
df.to_csv("ipl_cleaned.csv", index=False)